server:
  port: 8080
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hjc525437
mybatis:
  mapper-locations: classpath:mapper/*.xml